pub mod audio;
pub mod chunking;
pub mod cleanup;
pub mod cleanup_manager;
pub mod codemode;
pub mod config;
pub mod dictionary;
pub mod engine;
pub mod history;
pub mod hotkey;
pub mod insert;
pub mod ipc;
pub mod meeting;
pub mod model_manager;
pub mod models;
pub mod permissions;
pub mod profiles;
pub mod rolling;
pub mod snippets;

pub use audio::{AudioCommand, AudioRecorder, AudioReply};
pub use chunking::transcribe_long;
pub use config::Config;
pub use engine::{ParakeetTranscriber, Transcript, TranscriptSegment, Transcriber};
pub use models::{model_root_dir, parakeet_model_dir, ModelStatus};
